name: reactivity
description: >
  A minimal, elegant, and powerful reactive state management solution for Flutter.
  Built to be simple, intuitive, and fully compatible with Flutter's widget system.

version: 0.9.0
homepage: https://portifolio-alpha-orcin.vercel.app/
repository: https://github.com/FelipeKaian/reactivity

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # No assets or fonts needed for this package at the moment.
